[base]
db_type = gembase
idx = False
replicon_topology = circular
sequence_db = /Users/CAM920/Desktop/mab-plasmid-typing/pB_type_nucleotide.prt_defensefinder.prt
[models_opt]
[models]
models = defense-finder-models/DefenseFinder all
[hmmer]
coverage_profile = 0.4
e_value_search = 0.1
cut_ga = True
i_evalue_sel = 0.001
hmmer = /opt/miniconda3/envs/defensefinder/bin/hmmsearch
[score_opt]
mandatory_weight = 1.0
accessory_weight = 0.5
neutral_weight = 0.0
exchangeable_weight = 1.0
itself_weight = 1.0
redundancy_penalty = 1.5
out_of_cluster_weight = 0.7
[directories]
system_models_dir = /Users/CAM920/.macsyfinder/models
out_dir = /Users/CAM920/Desktop/mab-plasmid-typing/defense-finder-tmp/DefenseFinder
profile_suffix = .hmm
res_search_dir = .
res_search_suffix = .search_hmm.out
res_extract_suffix = .res_hmm_extract
[general]
log_file = macsyfinder.log
log_level = 20
relative_path = False
verbosity = 0
quiet = 0
mute = True
worker = 0
timeout = 0
force_run = False

